
service: hello

# frameworkVersion: ">=1.12.0"

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-python-requirements

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
  reply:
    handler: handler.reply
    events:
      - http:
          path: reply
          method: post
          cors: true
