---
service: domain
#app: your-app-name
#tenant: your-tenant-name

frameworkVersion: ">=1.44.1"

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: ap-northeast-1

custom:
  customDomain:
    domainName: api.gomesuit.me
    certificateName: '*.gomesuit.me'
    endpointType: 'regional'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-domain-manager
