---
service: aws-python3

frameworkVersion: "=1.X.X"

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  # deploymentBucket: sls-${self:service}-${self:provider.stage}-deployment

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
