---
service: aws-notice

frameworkVersion: ">=1.30.0"

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  environment:
    SLACK_HOOK_URL: ${ssm:/larning-serverless/aws-notice/SLACK_HOOK_URL}
    SLACK_CHANNEL: aws-notice

functions:
  hello:
    handler: handler.hello
  login:
    handler: handler.login
    events:
      - cloudwatchEvent:
          event:
            detail-type:
              - "AWS Console Sign In via CloudTrail"
