---
service: aws-notice

frameworkVersion: ">=1.30.0"

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  environment:
    SLACK_HOOK_URL: ${ssm:/larning-serverless/aws-notice/SLACK_HOOK_URL}
    SLACK_CHANNEL: aws-notice

functions:
  hello:
    handler: handler.hello
  login:
    handler: handler.login
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
              state:
                - pending
